<a href="https://colab.research.google.com/github/GronDS/suai/blob/master/module_4/practice_1/main.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Библиотека `NumPy`:

## Практическая работа

### Описание практической работы

В практической работе необходимо решить предложенные задачи по программированию – вписать свой код в ячейки после условий задач вместо комментария `### YOUR CODE HERE ###` в файле *PR#1_numpy.ipynb* и сохранить изменения, используя опцию *Save and Checkpoint* из вкладки меню *File* или кнопку *Save and Checkpoint* на панели инструментов. Ссылку на итоговый файл файл необходимо скинуть преподавателю на проверку.

Дан массив, содержащий баллы слушателей курса по английскому языку за вступительный экзамен. Слушатели распределены по 15 группам по 10 человек.

In [ ]:
import numpy as np
scores = np.array([[20, 40, 56, 80, 0, 5, 25, 27, 74, 1],
         [0, 98, 67, 100, 8, 56, 34, 82, 100, 7],
         [78, 54, 23, 79, 100, 0, 0, 42, 95, 83],
         [51, 50, 47, 23, 100, 94, 25, 48, 38, 77],
         [90, 87, 41, 89, 52, 0, 5, 17, 28, 99],
         [32, 18, 21, 18, 29, 31, 48, 62, 76, 22],
         [6, 0, 65, 78, 43, 22, 38, 88, 94, 100],
         [77, 28, 39, 41, 0, 81, 45, 54, 98, 12],
         [66, 0, 88, 0, 44, 0, 55, 100, 12, 11],
         [17, 70, 86, 96, 56, 23, 32, 49, 70, 80],
         [20, 24, 76, 50, 29, 40, 3, 2, 5, 11],
         [33, 63, 28, 40, 51, 100, 98, 87, 22, 30],
         [16, 54, 78, 12, 25, 35, 10, 19, 67, 0],
         [100, 88, 24, 33, 47, 56, 62, 34, 77, 53],
         [50, 89, 70, 72, 56, 29, 15, 20, 0, 0]])

### Задание 1

Посчитать, сколько слушателей получили 0 за вступительный экзамен.

In [ ]:
scores_0 = scores == 0
scores_0.sum()

13

### Задание 2

Посчитать, сколько слушателей получили балл выше 50.

In [ ]:
scores_50 = scores > 50
scores_50.sum()

64

### Задание 3

Посчитать, сколько человек получили балл не ниже 50, но не выше 70.

In [ ]:
scores_70 = (50 <= scores) & (scores <= 70)
scores_70.sum()

26

### Задание 4

Определить, в какой группе средний балл за вступительный экзамен выше.

In [ ]:
scores.mean(axis = 1).max()


57.9

### Задание 5

Сохранить баллы слушателей выше 0 в массив `nonzero`.

In [ ]:
nonzero = scores[scores != 0]
nonzero

array([ 20,  40,  56,  80,   5,  25,  27,  74,   1,  98,  67, 100,   8,
        56,  34,  82, 100,   7,  78,  54,  23,  79, 100,  42,  95,  83,
        51,  50,  47,  23, 100,  94,  25,  48,  38,  77,  90,  87,  41,
        89,  52,   5,  17,  28,  99,  32,  18,  21,  18,  29,  31,  48,
        62,  76,  22,   6,  65,  78,  43,  22,  38,  88,  94, 100,  77,
        28,  39,  41,  81,  45,  54,  98,  12,  66,  88,  44,  55, 100,
        12,  11,  17,  70,  86,  96,  56,  23,  32,  49,  70,  80,  20,
        24,  76,  50,  29,  40,   3,   2,   5,  11,  33,  63,  28,  40,
        51, 100,  98,  87,  22,  30,  16,  54,  78,  12,  25,  35,  10,
        19,  67, 100,  88,  24,  33,  47,  56,  62,  34,  77,  53,  50,
        89,  70,  72,  56,  29,  15,  20])

### Задание 6

Используя массив `nonzero`, определить минимальный балл за вступительный балл по всем группам.

In [ ]:
nonzero.min()

1

### Задание 7

Выбрать из массива `nonzero` только те значения, которые соответствуют продвинутому уровню знания языка – баллу за экзамен выше 80. Сохранить полученный результат в массив `advanced`. В заданиях 8-10 нужно работать с массивом `advanced`.

In [ ]:
advanced = nonzero[nonzero > 80]
advanced

array([ 98, 100,  82, 100, 100,  95,  83, 100,  94,  90,  87,  89,  99,
        88,  94, 100,  81,  98,  88, 100,  86,  96, 100,  98,  87, 100,
        88,  89])

### Задание 8

Определить размерность массива `advanced`.

In [ ]:
advanced.ndim

1

### Задание 9

Определить форму массива `advanced`.

In [ ]:
advanced.shape

(28,)

### Задание 10

На основе исходного массива `scores` создать булев массив `sto`, где `True` соответствует баллам за экзамен, равным 100, а `False` – всем остальным баллам.

In [ ]:
sto = (scores == 100)
sto

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False,  True, False, False, False, False,  True,
        False],
       [False, False, False, False,  True, False, False, False, False,
        False],
       [False, False, False, False,  True, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
         True],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False,  True, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, 

### Задание 11

На основе исходного массива `scores` вывести на экран оценки слушателей первых семи групп (включительно, должны быть 7 списков оценок).

In [ ]:
scores[0:7]

array([[ 20,  40,  56,  80,   0,   5,  25,  27,  74,   1],
       [  0,  98,  67, 100,   8,  56,  34,  82, 100,   7],
       [ 78,  54,  23,  79, 100,   0,   0,  42,  95,  83],
       [ 51,  50,  47,  23, 100,  94,  25,  48,  38,  77],
       [ 90,  87,  41,  89,  52,   0,   5,  17,  28,  99],
       [ 32,  18,  21,  18,  29,  31,  48,  62,  76,  22],
       [  6,   0,  65,  78,  43,  22,  38,  88,  94, 100]])

### Задание 12
Загрузить из файла массив `array_hw.npy` по [ссылке](https://drive.google.com/file/d/1q06WaAqjlyPuzZxQHKskGPf6S92-hJ7F/view?usp=sharing) и сохранить его как `arr`. Массив содержит объёмы продаж мороженого (в штуках) в 5 магазинах за одну неделю в июне (7 дней, с понедельника до воскресенья). В заданиях 2-5 нужно работать с массивом `arr`.

In [ ]:
arr = np.load('array_hw.npy')
arr

array([[100,  80,  70,  60, 120],
       [ 65,  55,  20,  50,  60],
       [ 80,  90,  75,  80,  60],
       [ 45,  60,  70,  20,  40],
       [ 82,  47,  56,  89,  92],
       [115, 120, 113, 106, 107],
       [ 46,  74,  23,  34,  19]])

### Задание 13
Если думать о массиве `arr` как о таблице, сейчас в таблице магазины идут по столбцам (1 магазин = 1 столбец, всего 5), а дни – по строкам (1 день = 1 строка, всего 7). Преобразовать массив `arr` таким образом, чтобы по строкам шли магазины, а по столбцам – дни (1 строка = 1 магазин). Сохранить изменения. Проверить, что форма массива изменилась.

In [ ]:
arr.shape

(7, 5)

In [ ]:
arr = arr.transpose()
arr

array([[100,  80,  70,  60, 120],
       [ 65,  55,  20,  50,  60],
       [ 80,  90,  75,  80,  60],
       [ 45,  60,  70,  20,  40],
       [ 82,  47,  56,  89,  92],
       [115, 120, 113, 106, 107],
       [ 46,  74,  23,  34,  19]])

In [ ]:
arr.shape

(7, 5)

### Задание 14

Давайте представим, что информация по продажам обновилась: оказалось, что пятый магазин в воскресенье продал не 19 порций мороженого, а 25, и второй магазин продал во вторник не 55 порций, а 65. Изменить массив `arr` в соответствии с этой информацией.

In [ ]:
arr[6][4] = 25
arr[1][1] = 65
arr


array([[100,  80,  70,  60, 120],
       [ 65,  65,  20,  50,  60],
       [ 80,  90,  75,  80,  60],
       [ 45,  60,  70,  20,  40],
       [ 82,  47,  56,  89,  92],
       [115, 120, 113, 106, 107],
       [ 46,  74,  23,  34,  25]])

### Задание 15

Посчитать суммарный объём продаж мороженого по всем магазинам.

In [ ]:
arr.sum()

2439

### Задание 16

Выгрузить обновлённый массив `arr` в txt-файл. Сам txt-файл загружать в систему не нужно, только написать соответствующий код в ipynb-файл.

In [ ]:
np.savetxt('arr.txt', arr)

### Задание 17
Дан массив `income`, содержащий значения прибыли магазина в тысячах на начало, середину и конец года, за четыре года подряд (значения никак не сгруппированы, можно считать, что они так выгрузились из файла).
Изменить форму массива так, чтобы значения были сгруппированы по три значения в каждом списке внутри массива (прибыль на начало, середину и конец года).

In [ ]:
# массив
income = np.array([1000, 2000, 3500,
                   2500, 1500, 3800,
                   1200, 9000, 12000,
                   4500, 6700, 11000])

In [ ]:
income.reshape(4,3)

array([[ 1000,  2000,  3500],
       [ 2500,  1500,  3800],
       [ 1200,  9000, 12000],
       [ 4500,  6700, 11000]])

### Задание 18
Создать список `turnout` (*list*, не массив), содержащий следующие значения явки на избирательные участки в процентах:

23.56, 45.78, 34.92, 57.34, 56.55, 67.23.

Создать, используя списковые включения и встроенные, не из `NumPy`, функции для округления, новый список `turnout_r`, который состоит из округлённых до первого знака после запятой значений явки из `turnout`.

In [ ]:
turnout = [23.56, 45.78, 34.92, 57.34, 56.55, 67.23]
turnout_r = [round(x, 1) for x in turnout]
print(turnout_r)

[23.6, 45.8, 34.9, 57.3, 56.5, 67.2]


### Задание 19
Выполнить те же операции, что и в предыдущей задаче, но с использованием массивов и функций `NumPy`. Другими словами, создать массив `turnout` и на его основе создать массив `turnout_r` с округлёнными до первого знака значениями явки.

In [ ]:
turnout = np.array([23.56, 45.78, 34.92, 57.34, 56.55, 67.23])
np.round(turnout, 1)

array([23.6, 45.8, 34.9, 57.3, 56.6, 67.2])

### Задание 20

Зайдите на [страницу](https://ru.wikipedia.org/wiki/%D0%9C%D0%B5%D0%B6%D0%B4%D1%83%D0%BD%D0%B0%D1%80%D0%BE%D0%B4%D0%BD%D1%8B%D0%B9_%D0%B8%D0%BD%D0%B4%D0%B5%D0%BA%D1%81_%D1%81%D1%87%D0%B0%D1%81%D1%82%D1%8C%D1%8F) Википедии, посвящённую Международному индексу счастья, выберите из таблицы **2012 Международный индекс счастья** любые 5 стран и любые 3 показателя и создайте структурированный массив `happy`, такой, в котором есть поле «название страны» и поля для трёх выбранных показателей. Выберите подходящий тип для каждого поля (показателя) в массиве и учтите это при создание структурированного массива. Выведите полученный массив на экран.

In [ ]:
happy = np.array([('Алжир', 26, 52.2, 73.1),
        ('Белиз', 3, 59.3, 76.1),
        ('Австрия', 48, 47.1, 80.9),
        ('Кыргызстан', 38, 49.1, 67.7),
        ('Новая Зеландия', 28, 51.6, 80.7)],
        dtype=[('Страна', '<U15'),
             ('Место в списке', int),
             ('HPI','<f4'),
             ('Ожидаемая продолжительность жизни','<f4')])
happy




array([('Алжир', 26, 52.2, 73.1), ('Белиз',  3, 59.3, 76.1),
       ('Австрия', 48, 47.1, 80.9), ('Кыргызстан', 38, 49.1, 67.7),
       ('Новая Зеландия', 28, 51.6, 80.7)],
      dtype=[('Страна', '<U15'), ('Место в списке', '<i8'), ('HPI', '<f4'), ('Ожидаемая продолжительность жизни', '<f4')])

### Задание 21
Сконвертируйте полученный в предыдущей задаче структурированный массив в обычный список и выведите на экран его второй элемент.

In [ ]:
happy.tolist()

[('Алжир', 26, 52.20000076293945, 73.0999984741211),
 ('Белиз', 3, 59.29999923706055, 76.0999984741211),
 ('Австрия', 48, 47.099998474121094, 80.9000015258789),
 ('Кыргызстан', 38, 49.099998474121094, 67.69999694824219),
 ('Новая Зеландия', 28, 51.599998474121094, 80.69999694824219)]

# Дополнительное  задание.



### Задание 1

Транспонировать массив `A`, не используя встроенных методов `NumPy`. Сохранить полученный массив в переменную `A_tr`. Допустимо использовать циклы и условные конструкции (при необходимости).

**Напоминание:** транспонирование – операция замены строк и столбцов местами. Пример:

До транспонирования:

        [[2, 5, 0],
        [7, 8, 1]]

После транспонирования:

        [[2, 7],
        [5, 8],
        [0, 1]]



In [ ]:
A = [[2, 5, 0],
    [7, 8, 1]]

A_tr = []

for i in range(len(A[0])):
  new_list = []
  for j in range(len(A)):
    new_list.append(A[j][i])
  A_tr.append(new_list)
print(A_tr)

[[2, 7], [5, 8], [0, 1]]


### Задание 2

Сравнить результаты: проверить равенство полученного выше массива `A_tr` и массива, который получается транспонированием массива `A` с помощью метода `.T`.

**Подсказка:** для сравнения массивов целиком, не поэлементно, можно использовать  `array_equal()`.

In [ ]:
A = np.array(A)
np.array_equal(A.T, A_tr)

True

### Задание 3

Студент N подрабатывает репетитором по математике и ведёт занятия разных типов: готовит к ЕГЭ, к олимпиадам, «подтягивает» математику у школьников младших классов.

В массиве `classes` хранится число проведённых уроков за пять рабочих дней, в массиве `prices` — стоимость одного урока (считаем, что студент за день проводит занятия одного типа, одинаковые по стоимости).

Определить доход студента за неделю, используя [метод](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) `.dot()` для нахождения [скалярного произведения](https://ru.wikipedia.org/wiki/%D0%A1%D0%BA%D0%B0%D0%BB%D1%8F%D1%80%D0%BD%D0%BE%D0%B5_%D0%BF%D1%80%D0%BE%D0%B8%D0%B7%D0%B2%D0%B5%D0%B4%D0%B5%D0%BD%D0%B8%D0%B5).

In [ ]:
classes = np.array([3, 3, 2, 0, 2])
prices = np.array([1500, 1500, 2500, 1000, 1000])

In [ ]:
np.dot(classes, prices)

16000

### Задание 4

По результатам работы с данными по оценкам за эссе студентов, поставленным двумя разными экспертами, были созданы два булевых массива `expert1` и `expert2`, в которых значение `True` означает оценку «удовлетворительно» и выше, а значение `False` – неудовлетворительно. Всего было оценено 15 эссе, по 5 эссе на каждую из трёх тем.

In [ ]:
expert1 = np.array([[True, False, False, True, True],
                   [False, True, False, False, True],
                   [True, True, True, False, False]])
expert2 = np.array([[True, False, False, False, True],
                   [False, False, False, False, False],
                   [True, False, True, False, False]])

In [ ]:
result = expert1 & expert2
result

array([[ True, False, False, False,  True],
       [False, False, False, False, False],
       [ True, False,  True, False, False]])

### Задание 5

Дан массив `essay` с итоговыми оценками студентов за эссе из задачи 4:

In [ ]:
# pass - сдал
# not pass - не сдал

essay = np.array([["pass", "not pass", "not pass", "not pass", "pass"],
        ["not pass", "not pass", "not pass", "not pass", "not pass"],
        ["pass", "not pass", "pass", "not pass", "not pass"]])

Проверить ответ в предыдущей задаче, используя массив `essay`. Решение должно
быть представлено в виде кода, не в виде выводов в результате явного подсчёта элементов.

In [ ]:
essay = np.where(essay == "pass", 1, essay )
essay = np.where(essay == "not pass", 0, essay )
essay = essay.astype(np.int8)
essay = essay.astype(np.bool_)
essay == result


array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

### Задание 6

Используя массивы `expert1` и `expert2` из задачи 4, определить согласованность двух экспертов, используя меру близости Жаккара, которая вычисляется следующим образом:

$$
J(A, B) = \frac{|A \cap B|}{|A| + |B| - |A \cap B|}
,$$

где $A$ – первое множество, $B$ – второе множество, $A \cap B$ – пересечение множеств, т.е. их общие элементы. Запись $|A|$ означает «количество элементов в множестве».

В качестве множеств $A$ и $B$ в данной задаче выступают множества (группы) студентов, которые получили зачёт у первого и второго экспертов.

In [ ]:
A =
A

True